### ISSUE TITLE
Credentials Encryption (Encripcion de Credenciales)

### ISSUE THREAD

**Issue by tr0b** [pieza/restapp#10]
### As an User
I would like my account credentials to be encrypted
In order to be at peace, knowing that my account's sensitive data is protected against attackers

### Key Objectives:
- Investigate how to implement basic hashing with either argon2 or bcrypt, in our backend
- Install either of this encryption solutions
- Implement them in our application's middleware during account registration and authentication
- Make sure credentials are protected from both ends (receiving and sending)

### Yo, como usuario
Quiero que las credenciales de mi cuenta esten encriptadas
Con el fin de estar en paz, sabiendo que la informacion sensible de mi cuenta se encuentra protegida

### Objetivos Clave:
- Investigar sobre como implementar hashing basico con argon2 o bcrypt
- Instalar en la aplicacion cualquiera de estas dos soluciones
- Implementarlas en el middleware de nuestro programa
- Estar seguros de que las credenciales se encuentran protegidas en ambos extremos (receptor y emisor)

**Comment by jdiax3004** [comment]
Esto va con la implementación de Passport
